OnlineEditorsExample/OnlineEditorsExampleRuby/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  match '/index',    to: 'home#index',    via: 'get'
  match '/editor',    to: 'home#editor',    via: 'get'
  match '/sample',    to: 'home#sample',    via: 'get'

  match '/upload',    to: 'home#upload',    via: 'post'
  match '/convert',    to: 'home#convert',    via: 'get'
  match '/save',    to: 'home#save',    via: 'get'
  match '/track',    to: 'home#track',    via: 'post'

end

OnlineEditorsExample/OnlineEditorsExampleRuby/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def editor

    DocumentHelper.init(request.remote_ip, request.base_url)

    @file = FileModel.new(:file_name => params[:fileName], :mode => params[:mode], :user_ip => request.remote_ip)

  end

  def sample

    DocumentHelper.init(request.remote_ip, request.base_url)

    file_name = DocumentHelper.create_demo(params[:fileExt])
    redirect_to :controller => 'home', :action => 'editor', :fileName => file_name

  end

  def upload

    DocumentHelper.init(request.remote_ip, request.base_url)

    begin
      http_posted_file = params[:file]
      file_name = http_posted_file.original_filename
      cur_size = http_posted_file.size

      if DocumentHelper.file_size_max < cur_size || cur_size <= 0
        raise 'File size is incorrect'
      end

      cur_ext = File.extname(file_name).downcase

      unless DocumentHelper.file_exts.include? cur_ext
        raise 'File type is not supported'
      end

      file_name = DocumentHelper.get_correct_name(file_name)

      File.open(DocumentHelper.storage_path(file_name, nil), 'wb') do |file|
        file.write(http_posted_file.read)
      end

      render :text =>  '{ "filename": "' + file_name + '"}'
    rescue => ex
      render :text =>  '{ "error": "' + ex.message + '"}'
    end

  end

  def convert

    begin
      file_name = params[:filename]
      file_uri = DocumentHelper.get_file_uri(file_name)
      extension = File.extname(file_name)
      internal_extension = DocumentHelper.get_internal_extension(FileUtility.get_file_type(file_name))

      if DocumentHelper.convert_exts.include? (extension)
        key = ServiceConverter.generate_revision_id(file_uri)
        percent, new_file_uri  = ServiceConverter.get_converted_uri(file_uri, extension.delete('.'), internal_extension.delete('.'), key, true)

        if percent != 100
          render :text => '{ "step" : "' + percent.to_s + '", "filename" : "' + file_name + '"}'
          return
        end

        correct_name = DocumentHelper.get_correct_name(File.basename(file_name, extension) + internal_extension)

        uri = URI.parse(new_file_uri)
        http = Net::HTTP.new(uri.host, uri.port)

        if new_file_uri.start_with?('https')
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        end

        req = Net::HTTP::Get.new(uri.request_uri)
        res = http.request(req)
        data = res.body

        if data == nil
          raise 'stream is null'
        end

        File.open(DocumentHelper.storage_path(correct_name, nil), 'wb') do |file|
          file.write(data)
        end

        file_name = correct_name
      end

      render :text => '{ "filename" : "' + file_name + '"}'
    rescue => ex
      render :text => '{ "error": "' + ex.message + '"}'
    end

  end

  def save

    download_uri = params[:fileuri]
    file_name = params[:filename]

    if download_uri == nil || file_name == nil || download_uri.empty? || file_name.empty?
      render :text => 'error'
      return
    end

    new_type = File.extname(download_uri).delete('.')
    current_type = (params[:filetype] == nil ? File.extname(file_name) : params[:filetype]).delete('.')

    if new_type.downcase != current_type.downcase

      key = ServiceConverter.generate_revision_id(download_uri)

      begin
          result, new_file_uri = ServiceConverter.get_converted_uri(download_uri, new_type, current_type, key, false)
          if result != 100
            raise 'error'
          end
      rescue
        render :text => 'error'
        return
      end

      download_uri = new_file_uri
      new_type = current_type

    end

    file_name = File.basename(file_name, current_type) + new_type

    begin

      uri = URI.parse(download_uri)
      http = Net::HTTP.new(uri.host, uri.port)

      if download_uri.start_with?('https')
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      end

      req = Net::HTTP::Get.new(uri.request_uri)
      res = http.request(req)
      data = res.body

      if data == nil
        raise 'stream is null'
      end

      File.open(DocumentHelper.storage_path(file_name, nil), 'wb') do |file|
        file.write(data)
      end

    rescue
      render :text => 'error'
      return
    end

    render :text => 'success'

  end

  def track

    user_address = params[:userAddress]
    file_name = params[:fileName]

    storage_path = DocumentHelper.storage_path(file_name, user_address)
    body = request.body.read

    if body == nil || body.empty?
      return
    end

    file_data = JSON.parse(body)
    status = file_data['status'].to_i

    if status == 2 || status == 3 #MustSave, Corrupted

      saved = 1

      begin

        download_uri = file_data['url']
        uri = URI.parse(download_uri)
        http = Net::HTTP.new(uri.host, uri.port)

        if download_uri.start_with?('https')
          http.use_ssl = true
          http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        end

        req = Net::HTTP::Get.new(uri.request_uri)
        res = http.request(req)
        data = res.body

        if data == nil
          raise 'stream is null'
        end

        File.open(storage_path, 'wb') do |file|
          file.write(data)
        end

      rescue
        saved = 0
      end

      render :text => '{"c":"saved","status":' + saved.to_s + '}'

    end

  end
end

OnlineEditorsExample/OnlineEditorsExampleRuby/app/helpers/home_helper.rb
module HomeHelper
end

OnlineEditorsExample/OnlineEditorsExampleRuby/app/views/home/editor.html.erb
<div class="form">
  <div id="iframeEditor">
  </div>
</div>

<script src="<%= Rails.configuration.urlApi %>"></script>

<script type="text/javascript" language="javascript">

    var docEditor;
    var fileName = "<%= @file.file_name %>";
    var fileType = "<%= @file.file_ext.delete('.') %>";

    var innerAlert = function (message) {
        if (console && console.log)
            console.log(message);
    };

    var onReady = function () {
        innerAlert("Document editor ready");
    };

    var onBack = function () {
        location.href = "<%= root_path %>";
    };

    var onDocumentStateChange = function (event) {
        var title = document.title.replace(/\*$/g, "");
        document.title = title + (event.data ? "*" : "");
    };

    var onRequestEditRights = function () {
        if (typeof DocsAPI.DocEditor.version == "function") {
            var version = DocsAPI.DocEditor.version();
            if ((parseFloat(version) || 0) >= 3) {
                location.href = location.href.replace(RegExp("action=view?&", "i"), "");
                return;
            }
        }
        docEditor.applyEditRights(true);
    };

    var onDocumentSave = function (event) {
        SaveFileRequest(fileName, fileType, event.data);
    };

    var onError = function (event) {
        if (console && console.log && event)
            console.log(event.data);
    };

    var сonnectEditor = function () {

        docEditor = new DocsAPI.DocEditor("iframeEditor",
                {
                    width: "100%",
                    height: "100%",

                    type: "<%= @file.desktop_type  ? 'desktop' : 'embedded' %>",
                    documentType: "<%= @file.document_type %>",
                    document: {
                        title: fileName,
                        url: "<%= @file.file_uri %>",
                        fileType: fileType,
                        key: "<%= @file.key %>",
                        vkey: "<%= @file.validate_key %>",

                        info: {
                            author: "Me",
                            created: "<%= Time.now.to_s %>"
                        },

                        permissions: {
                            edit: "<%= (DocumentHelper.edited_exts.include? @file.file_ext).to_s %>" == "true",
                            download: true
                        }
                    },
                    editorConfig: {
                        mode: "<%= (DocumentHelper.edited_exts.include? @file.file_ext) && @file.mode != 'view' ? 'edit' : 'view' %>",

                        lang: "en",

                        callbackUrl: "<%= raw @file.callback_url %>",

                        embedded: {
                            saveUrl: "<%= @file.file_uri %>",
                            embedUrl: "<%= @file.file_uri %>",
                            shareUrl: "<%= @file.file_uri %>",
                            toolbarDocked: "top"
                        }
                    },
                    events: {
                        'onReady': onReady,
                        'onBack': "<%= @file.desktop_type.to_s %>" == "true" ? onBack : undefined,
                        'onDocumentStateChange': onDocumentStateChange,
                        'onSave': onDocumentSave,
                        'onError': onError
                    }
                });
    };

    if (window.addEventListener) {
        window.addEventListener("load", сonnectEditor);
    } else if (window.attachEvent) {
        window.attachEvent("load", сonnectEditor);
    }

    function getXmlHttp() {
        var xmlhttp;
        try {
            xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
        } catch (e) {
            try {
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            } catch (ex) {
                xmlhttp = false;
            }
        }
        if (!xmlhttp && typeof XMLHttpRequest != 'undefined') {
            xmlhttp = new XMLHttpRequest();
        }
        return xmlhttp;
    }

    function SaveFileRequest(fileName, fileType, fileUri) {
        var req = getXmlHttp();
        if (console && console.log) {
            req.onreadystatechange = function () {
                if (req.readyState == 4) {
                    console.log(req.statusText);
                    if (req.status == 200) {
                        console.log(req.responseText);
                    }
                }
            };
        }

        var requestAddress = "<%= save_url %>"
                + "?filename=" + encodeURIComponent(fileName)
                + "&filetype=" + encodeURIComponent(fileType)
                + "&fileuri=" + encodeURIComponent(fileUri);
        req.open('get', requestAddress, true);

        req.send(fileUri);
    }

</script>

OnlineEditorsExample/OnlineEditorsExampleRuby/app/views/home/index.html.erb
<div class="top-panel"></div>
<div class="main-panel">
  <span class="portal-name">ONLYOFFICE™ Online Editors</span>
  <br />
  <br />
  <span class="portal-descr">Get started with a demo-sample of ONLYOFFICE™ Online Editors, the first html5-based editors. You may upload your own documents for testing using the "Choose file" button and selecting the necessary files on your PC.</span>

  <div class="file-upload button gray">
    <span>Choose file</span>
    <input type="file" id="fileupload" name="file" data-url="<%= upload_path %>" />
  </div>
  <label class="save-original">
    <input type="checkbox" id="checkOriginalFormat" />Save document in original format
  </label>
  <span class="question"></span>
  <br />
  <br />
  <br />
  <span class="try-descr">You are also enabled to view and edit documents pre-uploaded to the portal.</span>

  <ul class="try-editor-list">
    <li>
      <a href="<%= sample_path + '?fileExt=docx' %>" target="_blank" class="try-editor document">Sample Document</a>
    </li>
    <li>
      <a href="<%= sample_path + '?fileExt=xlsx' %>" target="_blank" class="try-editor spreadsheet">Sample Spreadsheet</a>
    </li>
    <li>
      <a href="<%= sample_path + '?fileExt=pptx' %>" target="_blank" class="try-editor presentation">Sample Presentation</a>
    </li>
  </ul>

  <br />
  <br />
  <br />
  <div class="help-block">
    <span>Want to learn how it works?</span>
    <br />
    Read the editor <a href="http://api.onlyoffice.com/editors/howitworks">API Documentation</a>
  </div>
  <br />
  <br />
  <br />
  <div class="help-block">
    <span>Any questions?</span>
    <br />
    Please, <a href="mailto:sales@onlyoffice.com">submit your request</a> and we'll help you shortly.
  </div>
</div>

<div id="hint">
  <div class="corner"></div>
  If you check this option the file will be saved both in the original and converted into Office Open XML format for faster viewing and editing. In other case the document will be overwritten by its copy in Office Open XML format.
</div>

<div id="mainProgress">
  <div id="uploadSteps">
    <span id="step1" class="step">1. Loading the file</span>
    <span class="step-descr">The file loading process will take some time depending on the file size, presence or absence of additional elements in it (macros, etc.) and the connection speed.</span>
    <br />
    <span id="step2" class="step">2. File conversion</span>
    <span class="step-descr">The file is being converted into Office Open XML format for the document faster viewing and editing.</span>
    <br />
    <span id="step3" class="step">3. Loading editor scripts</span>
    <span class="step-descr">The scripts for the editor are loaded only once and are will be cached on your computer in future. It might take some time depending on the connection speed.</span>
    <input type="hidden" name="hiddenFileName" id="hiddenFileName" />
    <br />
    <br />
    <span class="progress-descr">Please note, that the speed of all operations greatly depends on the server and the client locations. In case they differ or are located in differernt countries/continents, there might be lack of speed and greater wait time. The best results are achieved when the server and client computers are located in one and the same place (city).</span>
    <br />
    <br />
    <div class="error-message">
      <span></span>
      <br />
      Please select another file and try again. If you have questions please <a href="mailto:sales@onlyoffice.com">contact us.</a>
    </div>
  </div>
  <iframe id="embeddedView" src="" height="345px" width="600px" frameborder="0" scrolling="no" allowtransparency></iframe>
  <br />
  <div id="beginEmbedded" class="button disable">Embedded view</div>
  <div id="beginView" class="button disable">View</div>
  <div id="beginEdit" class="button disable">Edit</div>
  <div id="cancelEdit" class="button gray">Cancel</div>
</div>

<span id="loadScripts" data-docs="<%= Rails.configuration.urlPreloader %>"></span>

<div class="bottom-panel">&copy; Ascensio System SIA <%= Time.now.year %>. All rights reserved.</div>

<%= javascript_include_tag "application" %>

<script language="javascript" type="text/javascript">
    var ConvertExtList = '<%= DocumentHelper.convert_exts.join(",") %>';
    var EditedExtList = '<%= DocumentHelper.edited_exts.join(",") %>';
    var UrlConverter = '<%= convert_path %>';
    var UrlEditor = '<%= editor_path %>';
</script>